In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, accuracy_score
import numpy as np
from sklearn.cluster import KMeans


In [3]:

# Load the DataFrame from the pickle file
submissions = pd.read_pickle('output/openai_embedded_large.pkl')

In [4]:

# Preprocess the labels
label_encoder = LabelEncoder()

submissions['link_flair_text'] = label_encoder.fit_transform(submissions['link_flair_text'])
num_classes = len(label_encoder.classes_)


In [9]:

# Convert the embeddings and labels lists
X = submissions['embedding'].values
y = submissions['link_flair_text'].values

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,)


X

array([tensor([-0.0019, -0.0268, -0.0179,  ..., -0.0029, -0.0004,  0.0003]),
       tensor([ 0.0406, -0.0353, -0.0050,  ...,  0.0021, -0.0230, -0.0169]),
       tensor([-0.0059, -0.0053, -0.0058,  ...,  0.0003,  0.0078, -0.0062]),
       ...,
       tensor([ 3.9292e-02, -5.6507e-02, -1.3491e-02,  ..., -9.5682e-05,
                1.0389e-02,  1.0522e-02])                               ,
       tensor([-0.0361,  0.0064, -0.0077,  ..., -0.0166, -0.0454, -0.0109]),
       tensor([ 0.0299,  0.0148, -0.0077,  ...,  0.0020, -0.0178, -0.0084])],
      dtype=object)

In [14]:
# Define the neural network

# Define the pipeline
matrix = np.vstack(submissions['embedding'].values)
n_clusters = 2

kmeans = KMeans(n_clusters = n_clusters, random_state=42)
kmeans.fit(matrix)
submissions['cluster'] = kmeans.labels_ # from https://platform.openai.com/docs/guides/embeddings/use-cases

In [19]:
print(f'accuracy : {len(submissions[submissions['cluster'] == submissions['link_flair_text']])/len(submissions)*100:.2f}%')

accuracy : 44.92%
